=== MatrosMartz/vimdoku/public/locales/share/i18n-schema.json
{"$schema":"http://json-schema.org/draft-07/schema#","properties":{"$schema":{"const":"./i18n-schema.json"},"help_title":{"type":"string","pattern":"^(?=.*\\{\\|version\\|\\})(?=.*\\{\\|lastChange\\|\\}).*$"},"cmdDesc_pause":{"type":"string"},"cmdDesc_quit":{"type":"string"},"cmdDesc_help_main":{"type":"string"},"cmdDesc_help_suggest":{"type":"string"},"cmdDesc_help_withArg":{"type":"string","pattern":"^(?=.*\\{\\|subject\\|\\}).*$"},"cmdDesc_language_set":{"type":"string"},"cmdDesc_language_setSuggest":{"type":"string","pattern":"^(?=.*\\{\\|lang\\|\\}).*$"},"cmdDesc_language_show":{"type":"string"},"cmdDesc_resume1":{"type":"string"},"cmdDesc_resume2":{"type":"string"},"cmdDesc_set_resetAll":{"type":"string"},"cmdDesc_set_resetPref":{"type":"string","pattern":"^(?=.*\\{\\|pref\\|\\}).*$"},"cmdDesc_set_resetSuggest":{"type":"string"},"cmdDesc_set_setNonTogglePref":{"type":"string","pattern":"^(?=.*\\{\\|pref\\|\\}).*$"},"cmdDesc_set_setNonToggleSuggest":{"type":"string"},"cmdDesc_set_showAll":{"type":"string"},"cmdDesc_set_showDiffer":{"type":"string"},"cmdDesc_set_showPref":{"type":"string","pattern":"^(?=.*\\{\\|pref\\|\\}).*$"},"cmdDesc_set_showSuggest":{"type":"string"},"cmdDesc_set_suggest1":{"type":"string"},"cmdDesc_set_suggest2":{"type":"string"},"cmdDesc_set_toggleInvPref":{"type":"string","pattern":"^(?=.*\\{\\|pref\\|\\}).*$"},"cmdDesc_set_toggleInvSuggest":{"type":"string"},"cmdDesc_set_toggleOffPref":{"type":"string","pattern":"^(?=.*\\{\\|pref\\|\\}).*$"},"cmdDesc_set_toggleOffSuggest":{"type":"string"},"cmdDesc_set_toggleOnPref":{"type":"string","pattern":"^(?=.*\\{\\|pref\\|\\}).*$"},"cmdDesc_start_difficulty":{"type":"string","pattern":"^(?=.*\\{\\|difficulty\\|\\}).*$"},"cmdDesc_start_subject":{"type":"string"},"cmdDesc_write":{"type":"string"},"cmdDesc_writeAndQuit":{"type":"string"},"cmdDesc_writeLike":{"type":"string"},"form_reset":{"type":"string"},"form_save":{"type":"string"},"gameBtn_goBack":{"type":"string"},"gameBtn_new_text":{"type":"string"},"gameBtn_resume_disabledReason":{"type":"string"},"gameBtn_resume_text":{"type":"string"},"gameBtn_selectDifficulty":{"type":"string"},"gameBtn_start":{"type":"string"},"modes_insert":{"type":"string"},"modes_normal":{"type":"string"},"modes_notes":{"type":"string"},"modes_visual":{"type":"string"},"prefs_tabs_edit":{"type":"string"},"prefs_tabs_show":{"type":"string"},"prefs_accessibility_less":{"type":"string"},"prefs_accessibility_more":{"type":"string"},"prefs_accessibility_system":{"type":"string"},"prefs_groups_sudoku":{"type":"string"},"prefs_groups_user":{"type":"string"},"prefs_groups_vim":{"type":"string"},"prefs_names_autoNoteDeletion":{"type":"string"},"prefs_names_autoSave":{"type":"string"},"prefs_names_autoValidation":{"type":"string"},"prefs_names_colorSchema":{"type":"string"},"prefs_names_colorTheme":{"type":"string"},"prefs_names_contrast":{"type":"string"},"prefs_names_cursorBox":{"type":"string"},"prefs_names_cursorCol":{"type":"string"},"prefs_names_cursorRow":{"type":"string"},"prefs_names_highlight":{"type":"string"},"prefs_names_history":{"type":"string"},"prefs_names_iconTheme":{"type":"string"},"prefs_names_markRelatedNumbers":{"type":"string"},"prefs_names_motionReduce":{"type":"string"},"prefs_names_numbers":{"type":"string"},"prefs_names_relativeNumbers":{"type":"string"},"prefs_names_remainingNumbers":{"type":"string"},"prefs_names_timer":{"type":"string"},"prefs_schema_dark":{"type":"string"},"prefs_schema_light":{"type":"string"},"prefs_schema_system":{"type":"string"},"prefs_showToggle":{"type":"string"},"prefs_toggle_false":{"type":"string"},"prefs_toggle_true":{"type":"string"},"statusBar_modesDisabledReason":{"type":"string"},"statusBar_posDesc":{"type":"string","pattern":"^(?=.*\\{\\|col\\|\\})(?=.*\\{\\|row\\|\\}).*$"},"sync_false":{"type":"string"},"sync_true":{"type":"string"}},"required":["$schema","help_title","cmdDesc_pause","cmdDesc_quit","cmdDesc_help_main","cmdDesc_help_suggest","cmdDesc_help_withArg","cmdDesc_language_set","cmdDesc_language_setSuggest","cmdDesc_language_show","cmdDesc_resume1","cmdDesc_resume2","cmdDesc_set_resetAll","cmdDesc_set_resetPref","cmdDesc_set_resetSuggest","cmdDesc_set_setNonTogglePref","cmdDesc_set_setNonToggleSuggest","cmdDesc_set_showAll","cmdDesc_set_showDiffer","cmdDesc_set_showPref","cmdDesc_set_showSuggest","cmdDesc_set_suggest1","cmdDesc_set_suggest2","cmdDesc_set_toggleInvPref","cmdDesc_set_toggleInvSuggest","cmdDesc_set_toggleOffPref","cmdDesc_set_toggleOffSuggest","cmdDesc_set_toggleOnPref","cmdDesc_start_difficulty","cmdDesc_start_subject","cmdDesc_write","cmdDesc_writeAndQuit","cmdDesc_writeLike","form_reset","form_save","gameBtn_goBack","gameBtn_new_text","gameBtn_resume_disabledReason","gameBtn_resume_text","gameBtn_selectDifficulty","gameBtn_start","modes_insert","modes_normal","modes_notes","modes_visual","prefs_tabs_edit","prefs_tabs_show","prefs_accessibility_less","prefs_accessibility_more","prefs_accessibility_system","prefs_groups_sudoku","prefs_groups_user","prefs_groups_vim","prefs_names_autoNoteDeletion","prefs_names_autoSave","prefs_names_autoValidation","prefs_names_colorSchema","prefs_names_colorTheme","prefs_names_contrast","prefs_names_cursorBox","prefs_names_cursorCol","prefs_names_cursorRow","prefs_names_highlight","prefs_names_history","prefs_names_iconTheme","prefs_names_markRelatedNumbers","prefs_names_motionReduce","prefs_names_numbers","prefs_names_relativeNumbers","prefs_names_remainingNumbers","prefs_names_timer","prefs_schema_dark","prefs_schema_light","prefs_schema_system","prefs_showToggle","prefs_toggle_false","prefs_toggle_true","statusBar_modesDisabledReason","statusBar_posDesc","sync_false","sync_true"],"additionalProperties":false,"title":"vimdoku-${principal.name}-i18n","type":"object"}

=== MatrosMartz/vimdoku/public/locales/share/en.json
{
	"$schema": "./i18n-schema.json",
	"cmdDesc_help_main": "Open dialog and display the help app.",
	"cmdDesc_help_suggest": "Like \":help\", additionally jump to the tag {subject}.",
	"cmdDesc_help_withArg": "Open dialog and display the help of {|subject|}.",
	"cmdDesc_language_set": "Sets the current language to {lang}.",
	"cmdDesc_language_setSuggest": "Sets the current language to {|lang|}.",
	"cmdDesc_language_show": "Show the current value of language.",
	"cmdDesc_pause": "Pause the current game.",
	"cmdDesc_quit": "Close the current screen or dialog.",
	"cmdDesc_resume1": "Resume the current game.",
	"cmdDesc_resume2": "Resume the saved game only if no game active.",
	"cmdDesc_set_resetAll": "Reset all preferences.",
	"cmdDesc_set_resetPref": "Reset value of {|pref|}.",
	"cmdDesc_set_resetSuggest": "Reset {preference} to it's default value.",
	"cmdDesc_set_setNonTogglePref": "Assign to {|pref|} the {value}.",
	"cmdDesc_set_setNonToggleSuggest": "String or Number preference: Assign to {preference} the {value}.",
	"cmdDesc_set_showAll": "Show all preferences.",
	"cmdDesc_set_showDiffer": "Show all preferences that differ from their default value.",
	"cmdDesc_set_showPref": "Show value of {|pref|}.",
	"cmdDesc_set_showSuggest": "Show value of {preference}.",
	"cmdDesc_set_suggest1": "Toggle preference: Set, switch it on.",
	"cmdDesc_set_suggest2": "String or Number preference: Shows it's value",
	"cmdDesc_set_toggleInvPref": "Invert value of {|pref|}.",
	"cmdDesc_set_toggleInvSuggest": "Toggle preference: Invert value.",
	"cmdDesc_set_toggleOffPref": "Set, {|pref|} to switch off.",
	"cmdDesc_set_toggleOffSuggest": "Toggle preference: Set, switch it off.",
	"cmdDesc_set_toggleOnPref": "Set, {|pref|} to switch it on.",
	"cmdDesc_start_difficulty": "Start new game with the {|difficulty|} difficulty.",
	"cmdDesc_start_subject": "Start new game with the selected difficulty.",
	"cmdDesc_write": "Save the current game.",
	"cmdDesc_writeAndQuit": "Save the current game and close the current screen or dialog.",
	"cmdDesc_writeLike": "Like \":wq\", but save only when changes have been made.",
	"form_reset": "Reset to default values",
	"form_save": "Save all",
	"gameBtn_goBack": "Go back",
	"gameBtn_new_text": "New game",
	"gameBtn_resume_disabledReason": "No saved game.",
	"gameBtn_resume_text": "Resume game",
	"gameBtn_selectDifficulty": "Select difficulty",
	"gameBtn_start": "Start new game",
	"help_title": "For Vimdoku version {|version|}. last change: {|lastChange|}.",
	"modes_insert": "INSERT",
	"modes_normal": "NORMAL",
	"modes_notes": "NOTES",
	"modes_visual": "VISUAL",
	"prefs_accessibility_less": "Less",
	"prefs_accessibility_more": "More",
	"prefs_accessibility_system": "System",
	"prefs_groups_sudoku": "Sudoku",
	"prefs_groups_user": "User",
	"prefs_groups_vim": "Vim",
	"prefs_names_autoNoteDeletion": "Auto note deletion",
	"prefs_names_autoSave": "Auto save",
	"prefs_names_autoValidation": "Auto Validation",
	"prefs_names_colorSchema": "Color Schema",
	"prefs_names_colorTheme": "Color Theme",
	"prefs_names_contrast": "Contrast",
	"prefs_names_cursorBox": "Cursor box",
	"prefs_names_cursorCol": "Cursor column",
	"prefs_names_cursorRow": "Cursor row",
	"prefs_names_highlight": "Highlight",
	"prefs_names_history": "history",
	"prefs_names_iconTheme": "Icon Theme",
	"prefs_names_markRelatedNumbers": "mark Related Numbers",
	"prefs_names_motionReduce": "Motion reduce",
	"prefs_names_numbers": "Numbers",
	"prefs_names_relativeNumbers": "Relative numbers",
	"prefs_names_remainingNumbers": "Count remain Numbers",
	"prefs_names_timer": "Timer",
	"prefs_schema_dark": "dark",
	"prefs_schema_light": "Light",
	"prefs_schema_system": "System",
	"prefs_showToggle": "Show only that differ from default value",
	"prefs_tabs_edit": "Edit",
	"prefs_tabs_show": "Show",
	"prefs_toggle_false": "off",
	"prefs_toggle_true": "on",
	"statusBar_modesDisabledReason": "The insertion mode can only be changed on the game screen.",
	"statusBar_posDesc": "Row {|row|}, Col {|col|}.",
	"sync_false": "Unsaved",
	"sync_true": "Saved"
}

=== MatrosMartz/vimdoku/public/locales/share/es.json
{
	"$schema": "./i18n-schema.json",
	"cmdDesc_help_main": "Abre un dialogo y muestra las instrucciones de la aplicación.",
	"cmdDesc_help_suggest": "Parecido a \":help\", con la adicción de brincar a la etiqueta {subject}",
	"cmdDesc_help_withArg": "Abre un dialogo y muestra las instrucciones sobre {|subject|}",
	"cmdDesc_language_set": "Establece el lenguaje actual como {lang}.",
	"cmdDesc_language_setSuggest": "Establece el lenguaje actual como {|lang|}.",
	"cmdDesc_language_show": "Lenguaje",
	"cmdDesc_pause": "Pausa la partida actual.",
	"cmdDesc_quit": "Cierra la ventana o dialog actual.",
	"cmdDesc_resume1": "Continua con la partida actual.",
	"cmdDesc_resume2": "Continua con la partida guardada.",
	"cmdDesc_set_resetAll": "Restablece todas las preferencias",
	"cmdDesc_set_resetPref": "Restablece {|pref|} a su valor por defecto.",
	"cmdDesc_set_resetSuggest": "Restablece la preferencia a su valor por defecto.",
	"cmdDesc_set_setNonTogglePref": "Establece {value} como el valor de {|pref|}.",
	"cmdDesc_set_setNonToggleSuggest": "Preferencia de texto o numero: Establece {value} como su valor.",
	"cmdDesc_set_showAll": "Muestra todas las preferencias.",
	"cmdDesc_set_showDiffer": "Muestra todas las preferencias que difieren su valor por defecto.",
	"cmdDesc_set_showPref": "Muestra el valor de {|pref|}.",
	"cmdDesc_set_showSuggest": "Muestra el valor de la preferencia.",
	"cmdDesc_set_suggest1": "Preferencia de interruptor: Establecer valor, encender",
	"cmdDesc_set_suggest2": "Preferencia de texto o numero: Muestra su valor.",
	"cmdDesc_set_toggleInvPref": "Invierte el valor de {|pref|}",
	"cmdDesc_set_toggleInvSuggest": "Preferencia de interruptor: Invierte el valor.",
	"cmdDesc_set_toggleOffPref": "Establecer valor, apagar {|pref|}.",
	"cmdDesc_set_toggleOffSuggest": "Preferencia de interruptor: Establecer valor, apagar.",
	"cmdDesc_set_toggleOnPref": "Establecer valor, encender {|pref|}.",
	"cmdDesc_start_difficulty": "Inicia una nueva partida en la dificultad: {|difficulty|}.",
	"cmdDesc_start_subject": "Inicia una nueva partida con la dificultad seleccionada.",
	"cmdDesc_write": "Guarda la partida actual.",
	"cmdDesc_writeAndQuit": "Guarda la partida actual y cierra la ventana o dialogo actual.",
	"cmdDesc_writeLike": "Como \":wq\", pero solo si se han echo cambios.",
	"form_reset": "Restablece a los valores por defecto",
	"form_save": "Guarda Todo",
	"gameBtn_goBack": "Regresar",
	"gameBtn_new_text": "Nuevo juego",
	"help_title": "Para Vimdoku versión {|version|}. Ultimo cambio: {|lastChange|}.",
	"gameBtn_resume_disabledReason": "No hay partidas guardadas.",
	"gameBtn_resume_text": "Continuar la partida",
	"gameBtn_selectDifficulty": "Seleccionar dificultad",
	"gameBtn_start": "Iniciar nueva partida",
	"modes_insert": "INSERCIÓN",
	"modes_normal": "NORMAL",
	"modes_notes": "ANOTACIÓN",
	"modes_visual": "VISUAL",
	"prefs_accessibility_less": "Menos",
	"prefs_accessibility_more": "más",
	"prefs_accessibility_system": "Sistema",
	"prefs_groups_sudoku": "Sudoku",
	"prefs_groups_user": "Usuario",
	"prefs_groups_vim": "Vim",
	"prefs_names_autoNoteDeletion": "Notas auto eliminadas",
	"prefs_names_autoSave": "Auto guardado",
	"prefs_names_autoValidation": "Validación automática",
	"prefs_names_colorSchema": "Esquema de color",
	"prefs_names_colorTheme": "Tema de colores",
	"prefs_names_contrast": "Contraste",
	"prefs_names_cursorBox": "Caja de cursor",
	"prefs_names_cursorCol": "Columna de cursor",
	"prefs_names_cursorRow": "Fila de cursor",
	"prefs_names_highlight": "Resaltado",
	"prefs_names_history": "Historial",
	"prefs_names_iconTheme": "Tema de iconos",
	"prefs_names_markRelatedNumbers": "Marcar notas relacionadas",
	"prefs_names_motionReduce": "Reducción de movimiento",
	"prefs_names_numbers": "Números",
	"prefs_names_relativeNumbers": "Números relativos",
	"prefs_names_remainingNumbers": "Ver números restantes",
	"prefs_names_timer": "Temporizador",
	"prefs_schema_dark": "Obscuro",
	"prefs_schema_light": "Luminoso",
	"prefs_schema_system": "Sistema",
	"prefs_showToggle": "Muestra el valor actual del lenguaje.",
	"prefs_tabs_edit": "Editar",
	"prefs_tabs_show": "Visualizar",
	"prefs_toggle_false": "no",
	"prefs_toggle_true": "si",
	"statusBar_modesDisabledReason": "El modo de inserción solo puede ser cambiado en la pantalla de juego.",
	"statusBar_posDesc": "Fila {|row|}, Columna {|col|}.",
	"sync_false": "Sin guardar",
	"sync_true": "Guardado"
}
