=== MatrosMartz/vimdoku/public/locales/pages/help/main/i18n-schema.json
{"$schema":"http://json-schema.org/draft-07/schema#","properties":{"$schema":{"const":"./i18n-schema.json"},"about":{"type":"string"},"title":{"type":"string"},"moveAround_desc":{"type":"string"},"moveAround_title":{"type":"string"},"closeThisPage_desc":{"type":"string"},"closeThisPage_title":{"type":"string"},"getSpecificHelp_desc":{"type":"string"},"getSpecificHelp_helpContext":{"type":"string"},"getSpecificHelp_helpSummary":{"type":"string"},"getSpecificHelp_helpSyntax":{"type":"string"},"getSpecificHelp_title":{"type":"string"},"getSpecificHelp_table_head_example":{"type":"string"},"getSpecificHelp_table_head_prepend":{"type":"string"},"getSpecificHelp_table_head_what":{"type":"string"},"getSpecificHelp_table_cmdLineMode_example":{"type":"string"},"getSpecificHelp_table_cmdLineMode_prepend":{"type":"string"},"getSpecificHelp_table_cmdLineMode_what":{"type":"string"},"getSpecificHelp_table_insertMode_example":{"type":"string"},"getSpecificHelp_table_insertMode_what":{"type":"string"},"getSpecificHelp_table_normalMode_example":{"type":"string"},"getSpecificHelp_table_normalMode_what":{"type":"string"},"getSpecificHelp_table_notesMode_example":{"type":"string"},"getSpecificHelp_table_notesMode_what":{"type":"string"},"getSpecificHelp_table_preference_example":{"type":"string"},"getSpecificHelp_table_preference_what":{"type":"string"},"getSpecificHelp_table_visualMode_example":{"type":"string"},"getSpecificHelp_table_visualMode_what":{"type":"string"},"searchForHelp_desc":{"type":"string"},"searchForHelp_title":{"type":"string"}},"required":["$schema","about","title","moveAround_desc","moveAround_title","closeThisPage_desc","closeThisPage_title","getSpecificHelp_desc","getSpecificHelp_helpContext","getSpecificHelp_helpSummary","getSpecificHelp_helpSyntax","getSpecificHelp_title","getSpecificHelp_table_head_example","getSpecificHelp_table_head_prepend","getSpecificHelp_table_head_what","getSpecificHelp_table_cmdLineMode_example","getSpecificHelp_table_cmdLineMode_prepend","getSpecificHelp_table_cmdLineMode_what","getSpecificHelp_table_insertMode_example","getSpecificHelp_table_insertMode_what","getSpecificHelp_table_normalMode_example","getSpecificHelp_table_normalMode_what","getSpecificHelp_table_notesMode_example","getSpecificHelp_table_notesMode_what","getSpecificHelp_table_preference_example","getSpecificHelp_table_preference_what","getSpecificHelp_table_visualMode_example","getSpecificHelp_table_visualMode_what","searchForHelp_desc","searchForHelp_title"],"additionalProperties":false,"title":"vimdoku-${principal.name}-i18n","type":"object"}

=== MatrosMartz/vimdoku/public/locales/pages/help/en.json
{
	"$schema": "./i18n-schema.json",
	"about": "Vimdoku is a cross between the words <a href=\"en/intro#vim\">VIM</a> and <a href=\"en/intro#sudoku\">suDOKU</a>. Most of it is made by <a href=\"github.com/matrosmartz\">Matros Martz</a>, but you can contribute. <a href=\"en/help/contributing\">See how</a> (please, I don't know how to finish the documentation...).",
	"closeThisPage_desc": "Use <span class=\"highlight\"> <a href=\"en/help/editing#%3Aquit\"><span class=\"command\">q</span></a><span class=\"key\">Enter</span></span>.",
	"closeThisPage_title": "Close this page",
	"getSpecificHelp_desc": "It is possible to go directly to whatever you want <a href=\"en/help/help#help\">help</a> on, by giving an argument to the <span class=\"highlight\"><a href=\"en/help/help#%3Ahelp\"><span class=\"command\">help</span></a></span> command.",
	"getSpecificHelp_helpContext": "Prepend something to specify the context",
	"getSpecificHelp_helpSummary": "See <a href=\"en/help/usr_02#help-summary\">help-summary</a> for more contexts and an explication.",
	"getSpecificHelp_helpSyntax": "See <a href=\"en/help/intro#notation\">notation</a> for an explanation of the <a href=\"en/help/help#help\">help</a> syntax.",
	"getSpecificHelp_table_cmdLineMode_example": "<span class=\"highlight\"><a ahref=\"en/help/help#%3Ahelp\"><span class=\"command\">help</span></a><a href=\"en/help/editing#%3Aquit\"><span class=\"command\">quit</span></a></span>",
	"getSpecificHelp_table_cmdLineMode_prepend": "<a href=\"en/help/cmdLine#%3A\">:</a>",
	"getSpecificHelp_table_cmdLineMode_what": "<a href=\"en/help/cmdline#command-line\">Command-line</a> mode command",
	"getSpecificHelp_table_head_example": "ExAMPLE",
	"getSpecificHelp_table_head_prepend": "PREPEND",
	"getSpecificHelp_table_head_what": "WHAT",
	"getSpecificHelp_table_insertMode_example": "<span class=\"highlight\"><a href=\"en/help/help#%3Ahelp\"><span class=\"command\">help</span></a><a href=\"en/help/insert#i_<esc>\">i_<span class=\"key\">Esc</span></a></span>",
	"getSpecificHelp_table_insertMode_what": "<a href=\"en/help/insert#insert\">Insert</a> mode command",
	"getSpecificHelp_table_normalMode_example": "<span class=\"highlight\"><a href=\"en&/help/help#%3Ahelp\"><span class=\"command\">help</span></a> x</span>",
	"getSpecificHelp_table_normalMode_what": "<a href=\"en/help/intro#normal\">Normal</a> mode command",
	"getSpecificHelp_table_notesMode_example": "<span class=\"highlight\"><a href=\"en/help/help#%3Ahelp\"><span class=\"command\">help</span></a><a href=\"en/help/notes#n_<esc>\">n_<span class=\"key\">Esc</span></a></span>",
	"getSpecificHelp_table_notesMode_what": "<a href=\"en/help/notes#Notes\">Notes</a> mode command",
	"getSpecificHelp_table_preference_example": "<span class=\"highlight\"><a href=\"en/help/help#%3Ahelp\"><span class=\"command\">help</span></a><a href=\"en/help/options#%27autoSave%27\"><span class=\"text\">autoSave</span></a></span>",
	"getSpecificHelp_table_preference_what": "Preference",
	"getSpecificHelp_table_visualMode_example": "<span class=\"highlight\"><a href=\"en/help/help#%3Ahelp\"><span class=\"command\">help</span></a> v_u</span>",
	"getSpecificHelp_table_visualMode_what": "<a href=\"en/help/visual#visual\">Visual</a> mode command",
	"getSpecificHelp_title": "Get specific help",
	"moveAround_desc": "Use the cursor keys, or <a class=\"motion-letter\" href=\"en/help/motion#h\">h</a> to go left, <a class=\"motion-letter\" href=\"en/help/motion#j\">j</a> to go down, <a class=\"motion-letter\" href=\"en/help/motion#k\">k</a> to go up, <a class=\"motion-letter\" href=\"en/help/motion#l\">l</a> to go right.",
	"moveAround_title": "Move around",
	"searchForHelp_desc": "Type \"<span class=\"highlight\"><a href=\"en/help/help#%3Ahelp\"><span class=\"command\">help</span></a> <a href=\"en/help/motion/word\">word</a></span>\" then hit <span class=\"combination\"><a href=\"en/help/scroll#ctrl-d\">CTRL-D</a></span> to see matching entries <a href=\"en/help/help#help\">help</a> entries for \"<a href=\"en/help/motion/word\">word</a>\".",
	"searchForHelp_title": "Search for help",
	"title": "Main <a href=\"en/help/help#help\">help</a> file."
}

=== MatrosMartz/vimdoku/public/locales/pages/help/es.json
{
	"$schema": "./i18n-schema.json",
	"about": "Vimdoku es una combinación de las palabras <a href=\"en/intro#vim\">VIM</a> y <a href=\"en/intro#sudoku\">suDOKU</a>. La mayor parte fue creada por <a href=\"github.com/matrosmartz\">Matros Martz</a>, pero puedes contribuir. <a href=\"en/help/contributing\">Mira cómo</a> (por favor, no sé cómo terminar la documentación...).",
	"closeThisPage_desc": "Utiliza <span class=\"highlight\"> <a href=\"en/help/editing#%3Aquit\"><span class=\"command\">q</span></a><span class=\"key\">Enter</span></span>.",
	"closeThisPage_title": "Cerrar esta pagina",
	"getSpecificHelp_desc": "Es posible ir directamente a la <a href=\"en/help/help#help\">ayuda</a> que quieras, dando un argumento al comando <span class=\"highlight\"><a href=\"en/help/help#%3Ahelp\"><span class=\"command\">help</span></a></span>",
	"getSpecificHelp_helpContext": "Añade algo para especificar el contexto",
	"getSpecificHelp_helpSummary": "Ver <a href=\"en/help/usr_02#help-summary\">resumen de ayuda</a> para más contextos y una explicación.",
	"getSpecificHelp_helpSyntax": "Ver <a href=\"en/help/intro#notation\">notación</a> para una explicación de la sintaxis de la <a href=\"en/help/help#help\">ayuda</a>.",
	"getSpecificHelp_table_cmdLineMode_example": "<span class=\"highlight\"><a href=\"en/help/help#%3Ahelp\"><span class=\"command\">help</span></a> <a href=\"en/help/editing#%3Aquit\"><span class=\"command\">quit</span></a></span>",
	"getSpecificHelp_table_cmdLineMode_prepend": "<a href=\"en/help/cmdLine#%3A\">:</a>",
	"getSpecificHelp_table_cmdLineMode_what": "Comando del modo de <a href=\"en/help/cmdline#command-line\">línea de comandos</a>",
	"getSpecificHelp_table_head_example": "EJEMPLO",
	"getSpecificHelp_table_head_prepend": "ANTEPONER",
	"getSpecificHelp_table_head_what": "QUÉ",
	"getSpecificHelp_table_insertMode_example": "<span class=\"highlight\"><a href=\"en/help/help#%3Ahelp\"><span class=\"command\">help</span></a> <a href=\"en/help/insert#i_<esc>\">i_<span class=\"key\">Esc</span></a></span>",
	"getSpecificHelp_table_insertMode_what": "Comando del modo de <a href=\"en/help/insert#insert\">inserción</a>",
	"getSpecificHelp_table_normalMode_example": "<span class=\"highlight\"><a href=\"en/help/help#%3Ahelp\"><span class=\"command\">help</span></a> x</span>",
	"getSpecificHelp_table_normalMode_what": "Comando del modo <a href=\"en/help/intro#normal\">normal</a>",
	"getSpecificHelp_table_notesMode_example": "<span class=\"highlight\"><a href=\"en/help/help#%3Ahelp\"><span class=\"command\">help</span></a> <a href=\"en/help/notes#n_<esc>\">n_<span class=\"key\">Esc</span></a></span>",
	"getSpecificHelp_table_notesMode_what": "Comando del modo de <a href=\"en/help/notes#Notes\">notas</a>",
	"getSpecificHelp_table_preference_example": "<span class=\"highlight\"><a href=\"en/help/help#%3Ahelp\"><span class=\"command\">help</span></a> <a href=\"en/help/options#%27autoSave%27\"><span class=\"text\">autoSave</span></a></span>",
	"getSpecificHelp_table_preference_what": "Preferencia",
	"getSpecificHelp_table_visualMode_example": "<span class=\"highlight\"><a href=\"en/help/help#%3Ahelp\"><span class=\"command\">help</span></a> v_u</span>",
	"getSpecificHelp_table_visualMode_what": "Comando del modo <a href=\"en/help/visual#visual\">visual</a>",
	"getSpecificHelp_title": "Obtener ayuda específica",
	"moveAround_desc": "Utiliza las teclas de cursor, o <a class=\"motion-letter\" href=\"en/help/motion#h\">h</a> para ir a la izquierda, <a class=\"motion-letter\" href=\"en/help/motion#j\">j</a> para bajar, <a class=\"motion-letter\" href=\"en/help/motion#k\">k</a> para subir, <a class=\"motion-letter\" href=\"en/help/motion#l\">l</a> para ir a la derecha.",
	"moveAround_title": "Moverse por",
	"searchForHelp_desc": "Escribe «<span class=\"highlight\"><a href=\"en/help/help#%3Ahelp\"><span class=\"command\">help</span></a> <a href=\"en/help/motion/word\">word</a></span>» y luego presiona <span class=\"combination\"><a href=\"en/help/scroll#ctrl-d\">CTRL-D</a></span> para ver entradas coincidentes de la <a href=\"en/help/help#help\">ayuda</a> para «<a href=\"en/help/motion/word\">word (palabra)</a>».",
	"searchForHelp_title": "Buscar ayuda",
	"title": "Archivo principal de <a href=\"en/help/help#help\">ayuda</a>."
}
