=== MatrosMartz/vimdoku/public/locales/pages/home/i18n-schema.json
{"$schema":"http://json-schema.org/draft-07/schema#","properties":{"$schema":{"const":"./i18n-schema.json"},"cmd_help":{"type":"string"},"cmd_quit":{"type":"string"},"cmd_startGame":{"type":"string"},"cmd_startHelp":{"type":"string"},"cmd_type":{"type":"string"},"createBy":{"type":"string"},"desc":{"type":"string"},"version":{"type":"string"}},"required":["$schema","cmd_help","cmd_quit","cmd_startGame","cmd_startHelp","cmd_type","createBy","desc","version"],"additionalProperties":false,"title":"vimdoku-${principal.name}-i18n","type":"object"}

=== MatrosMartz/vimdoku/public/locales/pages/home/en.json
{
	"$schema": "./i18n-schema.json",
	"version": "Version",
	"createBy": "Created by",
	"desc": "Vimdoku is sudoku game with VIM shortcuts.",
	"cmd_help": "to on-line help.",
	"cmd_quit": "for exit.",
	"cmd_type": "Type",
	"cmd_startHelp": "for start command help.",
	"cmd_startGame": "for start game."
}

=== MatrosMartz/vimdoku/public/locales/pages/home/es.json
{
	"$schema": "./i18n-schema.json",
	"cmd_help": "para las instrucciones en linea.",
	"cmd_quit": "para salir.",
	"cmd_startGame": "para iniciar la partida.",
	"cmd_startHelp": "para las instrucciones del comando start.",
	"cmd_type": "Inserte",
	"createBy": "Creado por",
	"desc": "Vimdoku es un juego de sudoku con atajos de VIM.",
	"version": "Versi√≥n"
}
